const $=s=>document.querySelector(s);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const KEY='britain-portfolio-v1';let work=Portfolio.blank(COURSE),teacher=false,pendingImport=null,recovery=null,storageOk=true,fontPromise=null,pdfUrl=null,workUrl=null;
try{const raw=localStorage.getItem(KEY);if(raw)work=Portfolio.validate(JSON.parse(raw),COURSE);}catch{storageOk=false;}
const words=s=>s.trim()?s.trim().split(/\s+/).length:0;
let toastTimer;
function toast(message){clearTimeout(toastTimer);$('#toast').textContent=message;$('#toast').hidden=false;toastTimer=setTimeout(()=>$('#toast').hidden=true,6500);}
function save(){try{localStorage.setItem(KEY,JSON.stringify(Portfolio.wrap(work)));storageOk=true;$('#save-status').textContent='Auf diesem Gerät zwischengespeichert · bitte Datei sichern'}catch{storageOk=false;$('#save-status').textContent='Browserspeicher nicht verfügbar · bitte Arbeitsstand als Datei sichern';}}
function fieldMarkup(c,f){const value=work.chapters[c.id].answers[f[0]]||'';return `<div class="field full"><label for="answer-${f[0]}">${esc(f[1])}</label><textarea id="answer-${f[0]}" data-field="${f[0]}" maxlength="100000" ${f[3]==='long'?'class="writing"':''} placeholder="${esc(f[2])}">${esc(value)}</textarea>${f[3]==='long'?`<div class="word-count" data-count="${f[0]}">${words(value)} words</div>`:''}</div>`;}
function materialLinks(c){return c.materials.map(m=>`<a href="${esc(m.url)}" target="_blank" rel="noopener">${esc(m.label)} ↗</a>`).join('');}
function render(){
  $('#student').hidden=teacher;$('#teacher').hidden=!teacher;$('#role').textContent=teacher?'Lernendenansicht ↗':'Lehrkraftansicht ↗';
  if(teacher){renderTeacher();return;}
  const c=COURSE.find(c=>c.id===work.active),overview=!c;
  $('#overview').hidden=!overview;$('#lesson').hidden=overview;document.body.classList.toggle('in-chapter',!overview);document.querySelector('.skip-link').href=overview?'#overview':'#content';
  if(overview){
    $('#chapter-theme').innerHTML='GREAT BRITAIN · PAST & PRESENT <span>AUTUMN 2026</span>';
    $('#chapter-title').innerHTML='Power. Identity.<br><i>Belonging.</i>';
    $('#chapter-intro').textContent='Read Orwell, Kureishi and Smith. Explore who holds power, who belongs and who gets heard.';
    $('#chapter-meta').innerHTML='ENGLISH · YEAR 13 LK · HESSEN <span>5 lessons per week · until 22 December</span>';
    $('#overview').innerHTML=`<div class="overview-heading"><div><span class="eyebrow">YOUR LEARNING JOURNEY</span><h2>Fifteen chapters. Three perspectives.</h2></div><span class="tag">47 learning lessons + exam</span></div><div class="profile-fields" lang="de"><label>Name oder Kürzel <input id="learner-name" maxlength="200" autocomplete="off" value="${esc(work.profile.name)}" placeholder="Optional · erscheint im Export"></label><label>Klasse <input id="learner-group" maxlength="100" autocomplete="off" value="${esc(work.profile.group)}" placeholder="z. B. 13BG LK"></label></div>${scheduleMarkup()}<div class="chapter-grid">${COURSE.map((c,i)=>{const data=work.chapters[c.id];const count=Object.values(data.answers).filter(v=>v.trim()).length;return `<button class="chapter-card" data-chapter="${c.id}"><span class="chapter-number">${String(i+1).padStart(2,'0')}</span><span class="card-content"><span class="eyebrow">${esc(c.theme)}</span><strong>${esc(c.title)}</strong><span>${esc(c.question)}</span><small>Lessons ${c.lessons} · ${c.hours} ${c.hours===1?'lesson':'lessons'} · ${count?count+' entries':'Ready to explore'}</small></span><span class="card-arrow" aria-hidden="true">↗</span></button>`}).join('')}</div><section class="end-of-lesson" lang="de"><h2>Am Ende der Stunde</h2><p>„Arbeitsstand sichern“ speichert deine gesamte Reihe als bearbeitbare Datei. Lege sie in deinem Ordner ab. Zum Weiterarbeiten öffnest du diese Website und wählst „Arbeitsstand laden“. Exportiere eine PDF, wenn du Ergebnisse abgeben oder abheften möchtest.</p><p>Die Website übermittelt deine Antworten nicht automatisch an deine Lehrkraft. Teile deine PDF über den vereinbarten Abgabeweg, zum Beispiel IServ-Aufgaben.</p></section>`;
    $('#learner-name').oninput=e=>{work.profile.name=e.target.value;save()};$('#learner-group').oninput=e=>{work.profile.group=e.target.value;save()};
    document.querySelectorAll('[data-chapter]').forEach(b=>b.onclick=()=>openChapter(b.dataset.chapter));
  }else renderChapter(c);
  if(!storageOk)$('#save-status').textContent='Browserspeicher nicht verfügbar oder beschädigt · bitte Datei sichern';
}
function openChapter(id){if(!COURSE.some(c=>c.id===id))return;history.replaceState(null,'','#'+id);work.active=id;work.step=0;teacher=false;save();render();window.scrollTo({top:0,behavior:'smooth'});}
function overview(){history.replaceState(null,'','#overview');work.active='overview';work.step=0;teacher=false;save();render();window.scrollTo({top:0,behavior:'smooth'});}
function renderChapter(c){
  const data=work.chapters[c.id],stage=c.stages[work.step];
  $('#chapter-theme').innerHTML=esc(c.theme)+` <span>CHAPTER ${String(COURSE.indexOf(c)+1).padStart(2,'0')}</span>`;
  $('#chapter-title').textContent=c.title;$('#chapter-intro').textContent=c.intro;$('#chapter-meta').innerHTML=`Lessons ${c.lessons} · ${esc(c.product)} <span>${c.hours} ${c.hours===1?'lesson':'lessons'}</span>`;
  $('.steps').innerHTML=c.stages.map((s,i)=>`<button data-step="${i}" ${i===work.step?'aria-current="step"':''}><span>${String(i+1).padStart(2,'0')}</span>${esc(s.tab)}</button>`).join('');
  $('.steps').querySelectorAll('button').forEach(b=>b.onclick=()=>{work.step=+b.dataset.step;save();render();$('.steps').scrollIntoView({behavior:'smooth',block:'start'})});
  $('#content').innerHTML=`<div class="content-top"><span class="eyebrow">0${work.step+1} / ${esc(stage.tab).toUpperCase()}</span><span class="tag">${esc(c.product)}</span></div><h2>${esc(stage.title)}</h2><p class="lead">${esc(stage.text)}</p><p class="source source-reference">Reading: ${esc(c.source)}</p>${work.step===3?`<details class="answers-review"><summary>Read my work so far</summary>${c.stages.slice(0,3).flatMap(s=>s.fields).map(f=>`<h3>${esc(f[1])}</h3><div class="review-text">${esc(data.answers[f[0]]||'No entry yet.')}</div>`).join('')}</details>`:''}${stage.html||''}${stage.fields.map(f=>fieldMarkup(c,f)).join('')}${stage.checks?`<h3>My final check</h3>${stage.checks.map((s,i)=>`<label class="check"><input type="checkbox" data-check="${i}" ${data.checks[i]?'checked':''}>${esc(s)}</label>`).join('')}${data.feedback?`<div class="feedback"><strong>Feedback</strong><p>${esc(data.feedback)}</p></div>`:''}`:''}<div class="actions"><button class="secondary" id="previous-step">${work.step?'← Previous step':'← All chapters'}</button>${work.step<3?'<button class="primary" id="next-step">Continue →</button>':'<button class="primary" id="chapter-pdf">Export this chapter ↓</button>'}</div>${work.step===3?'<p class="source">Save an editable work file as well as your PDF. Neither button submits your work to a teacher.</p>':''}`;
  $('#content').querySelectorAll('[data-field]').forEach(t=>t.oninput=()=>{data.answers[t.dataset.field]=t.value;const count=$(`[data-count="${t.dataset.field}"]`);if(count)count.textContent=words(t.value)+' words';save()});
  $('#content').querySelectorAll('[data-check]').forEach(t=>t.onchange=()=>{data.checks[+t.dataset.check]=t.checked;save()});
  $('#previous-step').onclick=()=>{if(!work.step)overview();else{work.step--;save();render();$('.steps').scrollIntoView({behavior:'smooth'})}};
  if($('#next-step'))$('#next-step').onclick=()=>{work.step++;save();render();$('.steps').scrollIntoView({behavior:'smooth'})};
  if($('#chapter-pdf'))$('#chapter-pdf').onclick=()=>openPdf('current');
  $('#companion').innerHTML=`<div class="aside-heading">YOUR COMPANION <span>✦</span></div><section><span class="eyebrow">THE BIG QUESTION</span><h2>${esc(c.question)}</h2></section><details open><summary>Materials</summary><p class="source">${esc(c.source)}</p><div class="material-links">${materialLinks(c)}</div></details>${c.id==='crashcourse'?`<details class="practice-companion"><summary>Open practice text · The side entrance</summary>${PRACTICE_TEXT}</details>`:''}<details open><summary>Language toolkit</summary><dl>${c.toolkit.map(t=>`<dt>${esc(t[0])}</dt><dd>${esc(t[1])}</dd>`).join('')}</dl></details><details><summary>Useful phrases</summary><p>${esc(c.phrases)}</p></details><section class="note"><label for="notes">My pocket notes</label><textarea id="notes" maxlength="100000" placeholder="A thought, a question, a useful word…">${esc(data.notes)}</textarea><small>Included in your work file and PDF.</small></section>`;
  $('#notes').oninput=e=>{data.notes=e.target.value;save()};
}
function scheduleMarkup(){return `<details class="schedule-panel"><summary>Course calendar · exam on 6 November</summary><p>Planungsstart: 28.09.2026. Fünf Unterrichtsstunden à 45 Minuten pro voller Schulwoche, typischerweise 2 + 2 + 1. Der 24.–25.09. kann als zusätzlicher Einstieg genutzt werden. Konkrete Wochentage und schulinterne Ausfälle sind noch nicht eingetragen.</p><div class="schedule-wrap"><table class="schedule-table"><thead><tr><th>Week</th><th>Lessons</th><th>Focus & milestone</th></tr></thead><tbody>${[
['28 Sep – 02 Oct','01–05','Orwell: complete reading; pressure, language and symbolism'],
['05–17 Oct','Autumn break','No regular lessons planned'],
['19–23 Oct','06–10','Finish Orwell; read all of My Son the Fanatic; establish characters'],
['26–30 Oct','11–15','Restaurant scene, perspective, comparison; first two workshop lessons'],
['02–06 Nov','16–20','Finish workshop (2 lessons); EXAM 06.11. (3 lessons provisionally reserved)'],
['09–13 Nov','21–25','Feedback; Parvez, Bettina, title and ending; creative writing'],
['16–20 Nov','26–30','Diversity, dated sources, migration debate and blog'],
['23–27 Nov','31–35','Smith: author, listening, shared reading, six guiding questions'],
['30 Nov – 04 Dec','36–40','Cambodia: 15-minute presentation; five expert groups'],
['07–11 Dec','41–45','Group synthesis; narrative voice; three-text comparison'],
['14–18 Dec','46–50','Post-reading transfer and final portfolio'],
['21–22 Dec','Flexible buffer','Conferences and completion, depending on the timetable']
].map(r=>`<tr>${r.map(x=>`<td>${x}</td>`).join('')}</tr>`).join('')}</tbody></table></div><p>50 UStd. = 47 Lernstunden + vorläufig 3 Klausurstunden. Die tatsächliche Klausurdauer legt die Lehrkraft fest. 21.–22.12. sind nicht in die 50 Stunden eingerechnet. Herbstferien 05.–17.10.; Weihnachtsferien ab 23.12.2026. <a href="https://kultus.hessen.de/schulsystem/ferien/ferientermine" target="_blank" rel="noopener">Hessischer Ferienkalender ↗</a></p></details>`;}
function renderTeacher(){
 $('#teacher').innerHTML=`<div class="teacher-heading" lang="de"><div><div class="eyebrow">UNTERRICHTSPLAN · HERBST 2026</div><h1>Vom Empire zur Zugehörigkeit.</h1><p>Englisch LK 13 · 5 UStd. pro Woche · Klausur 06.11.2026</p></div><button class="primary" id="return-student">Zur Lernansicht</button></div><div class="teacher-notice" lang="de"><strong>Planung und dateibasiertes Feedback</strong><p>Diese Ansicht ist offen zugänglich. Sie zeigt nur den auf diesem Gerät geöffneten Arbeitsstand. Keine automatische Abgabe und kein Klassenkonto. Übungshinweise sind Lernhilfen; eine echte Klausur oder vertrauliche Musterlösung ist hier nicht hinterlegt.</p><button class="quiet" id="teacher-load">Arbeitsstand laden</button><button class="quiet" id="teacher-save">Arbeitsstand mit Feedback sichern</button></div>${scheduleMarkup()}<div class="reading-card"><h3>Bis zur Klausur am 6. November</h3><p>Shooting an Elephant ist vollständig gelesen und analysiert (7 UStd.). My Son the Fanatic ist vollständig gelesen und hinsichtlich Figuren, Restaurantdialog und Perspektive erschlossen (5 UStd.). Ein expliziter Vergleich (1 UStd.) und der Crashcourse (4 UStd.) führen zur Klausur. Die Vertiefung von My Son folgt danach.</p><h3>Materialtreue und Differenzierung</h3><p>Die Empire-Vorentlastung ist abgeschlossen. Seitenangaben beziehen sich auf die gedruckten Seiten im Heft; der PDF-Zähler liegt zwei Seiten darüber. Bei Cambodia gilt die eigene siebenseitige PPT, nicht die ältere 28-Folien-Version im ZIP. Scaffolds können zunächst geschlossen bleiben; stärkere Lernende prüfen Gegenbelege und alternative Deutungen. Vorbereitung und Überarbeitung zu Hause sind in den Kapiteln ausgewiesen.</p></div>${COURSE.map(c=>`<details class="teacher-unit"><summary><span>${c.lessons}</span> ${esc(c.title)} <small>${c.hours} UStd.</small></summary><p class="lead">${esc(c.teaching)}</p><p class="source">${esc(c.source)}</p><h3>Aktuell geöffnete Arbeit: ${esc(work.profile.name||'ohne Namensangabe')}</h3>${c.stages.flatMap(s=>s.fields).map(f=>`<h4>${esc(f[1])}</h4><div class="review-text">${esc(work.chapters[c.id].answers[f[0]]||'Noch kein Eintrag.')}</div>`).join('')}<div class="field full"><label for="feedback-${c.id}">Rückmeldung zu diesem Kapitel</label><textarea id="feedback-${c.id}" data-feedback="${c.id}" maxlength="100000">${esc(work.chapters[c.id].feedback)}</textarea></div></details>`).join('')}`;
 $('#return-student').onclick=()=>{teacher=false;render();window.scrollTo({top:0,behavior:'smooth'})};$('#teacher-load').onclick=()=>$('#work-file').click();$('#teacher-save').onclick=saveFile;
 document.querySelectorAll('[data-feedback]').forEach(t=>t.oninput=()=>{work.chapters[t.dataset.feedback].feedback=t.value;save()});
}
function timestamp(){return new Date().toISOString().replace(/[:.]/g,'-').slice(0,19);}
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();return url;}
function saveFile(){
  const blob=new Blob([JSON.stringify(Portfolio.wrap(work),null,2)],{type:'application/json'}),name=`britain-${timestamp()}.britain.json`;if(workUrl)URL.revokeObjectURL(workUrl);workUrl=download(blob,name);
  $('#file-result').hidden=false;$('#file-result').innerHTML=`Arbeitsdatei erstellt. Lege sie in deinem Ordner ab. <a href="${workUrl}" download="${name}">Datei nochmals herunterladen</a>`;
  toast('Arbeitsdatei erstellt. Bitte im Download- oder Teilen-Dialog in deinem Ordner sichern.');
}
async function loadFile(file){
  try{if(!file)return;if(file.size>8*1024*1024)throw new Error('Diese Datei ist zu groß. Bitte eine Projektdatei bis 8 MB auswählen.');let parsed;try{parsed=JSON.parse(await file.text())}catch{throw new Error('Die Datei konnte nicht gelesen werden. Bitte eine unveränderte .britain.json-Datei auswählen.');}
    pendingImport=Portfolio.validate(parsed,COURSE);const entries=Object.values(pendingImport.chapters).reduce((n,c)=>n+Object.values(c.answers).filter(v=>v.trim()).length,0);
    $('#import-preview').innerHTML=`<p><strong>${esc(file.name)}</strong></p><p>Name: ${esc(pendingImport.profile.name||'ohne Angabe')} · Klasse: ${esc(pendingImport.profile.group||'ohne Angabe')}</p><p>${entries} Antwortfelder in ${COURSE.length} Kapiteln. Notizen, Checklisten, Rückmeldungen, Textmarkierungen und Seitennotizen werden mitgeladen.</p>`;$('#import-dialog').showModal();
  }catch(e){pendingImport=null;toast(e.message);$('#file-result').hidden=false;$('#file-result').textContent=e.message;}
}
$('#confirm-import').onclick=()=>{if(!pendingImport)return;recovery=structuredClone(work);work=pendingImport;pendingImport=null;save();$('#import-dialog').close();teacher=false;render();$('#file-result').hidden=false;$('#file-result').innerHTML='Arbeitsstand geladen. <button class="quiet" id="undo-import">Laden rückgängig machen</button>';$('#undo-import').onclick=()=>{if(!recovery)return;work=recovery;recovery=null;save();render();$('#file-result').textContent='Vorheriger Arbeitsstand wiederhergestellt.';};toast('Arbeitsstand geladen. Du kannst direkt weiterarbeiten.');};
$('#cancel-import').onclick=()=>{pendingImport=null;$('#import-dialog').close()};$('#before-import').onclick=saveFile;
$('#work-file').onchange=e=>{loadFile(e.target.files[0]);e.target.value=''};
function openPdf(scope='all'){const current=COURSE.some(c=>c.id===work.active);$('#pdf-scope').querySelector('[value="current"]').disabled=!current;$('#pdf-scope').value=scope==='current'&&current?'current':'all';$('#pdf-status').textContent='';$('#pdf-dialog').showModal();}
async function font(){if(!fontPromise)fontPromise=fetch('NotoSans-Regular.ttf').then(r=>{if(!r.ok)throw new Error('Die PDF-Schrift konnte nicht geladen werden. Bitte die Verbindung prüfen und erneut versuchen.');return r.arrayBuffer()}).then(b=>{let str='';const a=new Uint8Array(b);for(let i=0;i<a.length;i+=8192)str+=String.fromCharCode(...a.subarray(i,i+8192));return btoa(str)}).catch(e=>{fontPromise=null;throw e});return fontPromise;}
$('#create-pdf').onclick=async()=>{
  $('#create-pdf').disabled=true;$('#pdf-status').textContent='PDF wird auf deinem Gerät erstellt…';
  try{if(!window.jspdf?.jsPDF)throw new Error('Die PDF-Funktion konnte nicht geladen werden. Bitte die Seite neu laden; sichere vorher deinen Arbeitsstand.');const snapshot=structuredClone(work),scope=$('#pdf-scope').value==='current'?snapshot.active:'all';const doc=Portfolio.makePdf(window.jspdf.jsPDF,snapshot,COURSE,scope,await font());const blob=doc.output('blob'),name=`britain-${scope==='all'?'portfolio':scope}-${timestamp()}.pdf`;if(pdfUrl)URL.revokeObjectURL(pdfUrl);pdfUrl=download(blob,name);$('#pdf-dialog').close();$('#file-result').hidden=false;$('#file-result').innerHTML=`PDF erstellt. <a href="${pdfUrl}" target="_blank" rel="noopener">PDF öffnen ↗</a> <a href="${pdfUrl}" download="${name}">PDF herunterladen ↓</a>`;const file=new File([blob],name,{type:'application/pdf'});if(navigator.canShare?.({files:[file]})){const b=document.createElement('button');b.className='quiet';b.textContent='Teilen / In Dateien sichern';b.onclick=async()=>{try{await navigator.share({files:[file],title:'Great Britain portfolio'})}catch(e){if(e.name!=='AbortError')toast('Bitte „PDF öffnen“ und den Teilen-Dialog des Browsers verwenden.')}};$('#file-result').append(b)}toast('PDF erstellt. Zum Weiterarbeiten zusätzlich die Arbeitsdatei sichern.');
  }catch(e){$('#pdf-status').textContent=e.message;}finally{$('#create-pdf').disabled=false;}
};
$('#cancel-pdf').onclick=()=>$('#pdf-dialog').close();$('#save-work').onclick=saveFile;$('#load-work').onclick=()=>$('#work-file').click();$('#export-pdf').onclick=()=>openPdf();$('#overview-link').onclick=overview;$('#back-overview').onclick=overview;$('.brand').onclick=e=>{e.preventDefault();overview()};$('#role').onclick=()=>{teacher=!teacher;render();window.scrollTo({top:0,behavior:'smooth'})};
let pencilMode=false;try{pencilMode=localStorage.getItem('britain-pencil-mode')==='true'}catch{}
function applyPencil(){document.body.classList.toggle('pencil-mode',pencilMode);$('#pencil-mode').setAttribute('aria-pressed',String(pencilMode));$('#pencil-mode').textContent=pencilMode?'✎ Apple Pencil · on':'✎ Apple Pencil';$('#pencil-guide').hidden=!pencilMode;}
$('#pencil-mode').onclick=()=>{pencilMode=!pencilMode;applyPencil();if(pencilMode)$('#pencil-guide').open=true;try{localStorage.setItem('britain-pencil-mode',String(pencilMode))}catch{}};
$('#quick-start').onclick=()=>openChapter('empire-officer');$('#quick-crash').onclick=()=>openChapter('crashcourse');
const deepLink=location.hash.slice(1);if(COURSE.some(c=>c.id===deepLink)&&work.active!==deepLink){work.active=deepLink;work.step=0;}
render();applyPencil();
if(document.modelContext?.registerTool){try{document.modelContext.registerTool({name:'get_learning_station_state',description:'Read the active chapter, step and count of filled fields in the local Great Britain portfolio.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute(input){if(!input||Object.keys(input).length)throw new Error('Expected an empty object');return {chapter:work.active,step:work.step+1,entries:Object.values(work.chapters).reduce((n,c)=>n+Object.values(c.answers).filter(v=>v.trim()).length,0),storage:'browser-local with project-file export'}}})}catch{}}
