/* Quiz responses, shared records and optional writing feedback. */
const LearningExtras=(()=>{
 let dialog,recordId,recordUrl,requestPending=false;
 const labels={claims:'Agreed conclusions',evidence:'Evidence · quotations, pages and lines',dissent:'Alternative readings & open questions',takeaway:'Our takeaway & next step'};
 function quizMarkup(c,q){const state=work.chapters[c.id].quiz[q.id]||{answers:q.items.map(()=>null),checked:false};return `<section class="reading-quiz" data-quiz="${q.id}" aria-labelledby="quiz-${q.id}"><span class="eyebrow">BASIC UNDERSTANDING · 3–5 MIN</span><h3 id="quiz-${q.id}">${esc(q.title)}</h3><p>Answer first, then check. Revisit the text if you are unsure. These are practice checks, not grades.${q.id.startsWith('beyond-')&&q.stage===0?' Complete only the quiz for your chosen extract.':''}</p>${q.items.map((x,i)=>`<fieldset><legend>${i+1}. ${esc(x.prompt)}</legend>${x.type==='match'?`<label for="quiz-${q.id}-${i}">${esc(x.group||"Complete the sentence")}</label><select id="quiz-${q.id}-${i}" data-qi="${i}"><option value="">Choose the matching ending…</option>${x.options.map((o,j)=>`<option value="${j}" ${state.answers[i]===j?'selected':''}>${esc(o)}</option>`).join('')}</select>`:x.options.map((o,j)=>`<label class="quiz-option"><input type="radio" name="quiz-${q.id}-${i}" data-qi="${i}" value="${j}" ${state.answers[i]===j?'checked':''}>${esc(o)}</label>`).join('')}${state.checked?`<p class="quiz-explanation ${state.answers[i]===x.answer?'correct':'retry'}"><b>${state.answers[i]===x.answer?'Correct.':'Revisit this.'}</b> ${esc(x.explanation)} <span>Answer: ${esc(x.options[x.answer])}</span></p>`:''}</fieldset>`).join('')}<div class="actions"><button class="primary" data-check-quiz>Check answers</button><button class="quiet" data-reset-quiz>Try again</button></div><p role="status" class="quiz-status">${state.checked?`${state.answers.filter((a,i)=>a===q.items[i].answer).length} / ${q.items.length} correct. Review the explanations, then retry if needed.`:''}</p></section>`;}
 function bindQuiz(el,c,q){const data=work.chapters[c.id];data.quiz[q.id]||={answers:q.items.map(()=>null),checked:false};const state=data.quiz[q.id];
 el.querySelectorAll('[data-qi]').forEach(input=>input.onchange=()=>{state.answers[+input.dataset.qi]=input.value===''?null:+input.value;state.checked=false;el.querySelectorAll('.quiz-explanation').forEach(n=>n.remove());el.querySelector('.quiz-status').textContent='Answer changed — check again when ready.';save();});
 el.querySelector('[data-check-quiz]').onclick=()=>{if(state.answers.some(x=>x===null)){el.querySelector('.quiz-status').textContent='Please answer every item first.';return;}state.checked=true;save();replace();};
 el.querySelector('[data-reset-quiz]').onclick=()=>{state.answers=q.items.map(()=>null);state.checked=false;save();replace();};
 function replace(){const box=document.createElement('div');box.innerHTML=quizMarkup(c,q);const next=box.firstElementChild;el.replaceWith(next);bindQuiz(next,c,q);next.querySelector('.quiz-status').setAttribute('tabindex','-1');next.querySelector('.quiz-status').focus({preventScroll:true});}
 }
 function mount(c,step){
  const content=document.querySelector('#content'),actions=content.querySelector(':scope > .actions');
  const qs=(READING_QUIZZES[c.id]||[]).filter(q=>q.stage===step);
  for(const q of qs){actions.insertAdjacentHTML('beforebegin',quizMarkup(c,q));bindQuiz(content.querySelector(`[data-quiz="${q.id}"]`),c,q);}
  if(step===3){actions.insertAdjacentHTML('beforebegin',`<section class="plenary-card"><span class="eyebrow">CHAPTER WRAP-UP · TOGETHER</span><h3>${esc(PLENARY[c.id].title)}</h3><p>${esc(PLENARY[c.id].focus)}</p><p>Bring your strongest finding and one piece of evidence. Compare, qualify and record what the class can agree on.</p><button class="primary" id="open-plenary">Plenumssicherung öffnen →</button><p class="source">Drei Methoden zur Auswahl · gemeinsames Protokoll · separater Export</p></section>`);document.querySelector('#open-plenary').onclick=()=>openPlenary(c.id);}
  const shortcut=document.createElement('button');shortcut.className='quiet plenary-shortcut';shortcut.textContent='Gemeinsame Sicherung ↗';shortcut.onclick=()=>openPlenary(c.id);document.querySelector('#companion').append(shortcut);
  for(const f of c.stages[step].fields.filter(f=>f[3]==='long'))mountAI(c,f);
 }
 function ensureDialog(){if(dialog)return;dialog=document.createElement('dialog');dialog.id='plenary-dialog';dialog.className='plenary-dialog';dialog.setAttribute('aria-labelledby','plenary-title');document.body.append(dialog);}
 function openPlenary(id){ensureDialog();recordId=id;const c=COURSE.find(c=>c.id===id),plan=PLENARY[id],p=work.chapters[id].plenary;
 dialog.innerHTML=`<div class="plenary-header"><div><span class="eyebrow">SHARED CLASS RECORD</span><h2 id="plenary-title">${esc(plan.title)}</h2></div><button class="quiet" id="close-plenary">Schließen ×</button></div><p>${esc(plan.focus)}</p><label for="plenary-variant">Plenumsvariante</label><select id="plenary-variant">${plan.variants.map((v,i)=>`<option value="${i}" ${p.variant===i?'selected':''}>${esc(v.name)} · ${v.minutes}</option>`).join('')}</select><div id="plenary-method" class="reading-card"></div><p><b>Precision check:</b> ${esc(plan.pitfall)}</p><p class="source" lang="de">Gemeinsam am projizierten Gerät ausfüllen. Das Protokoll bleibt auf diesem Gerät und in der Arbeitsdatei. Kein automatischer Abgleich zwischen Geräten. Die separate Sicherungs-PDF enthält ausschließlich diese vier Ergebnisfelder, keine persönlichen Antworten. Über euren Kurskanal teilen.</p>${Object.entries(labels).map(([k,label])=>`<div class="field full"><label for="plenary-${k}">${label}</label><textarea id="plenary-${k}" data-plenary-field="${k}" maxlength="100000">${esc(p[k])}</textarea></div>`).join('')}<div class="actions"><button class="primary" id="plenary-pdf">Sicherung als PDF ↓</button><button class="quiet" id="plenary-text">Sicherung als Text ↓</button><button class="quiet" id="plenary-save">Arbeitsstand sichern ↓</button></div><p id="plenary-status" role="status"></p>`;
 function method(){const v=plan.variants[p.variant];dialog.querySelector('#plenary-method').textContent=v.steps;}
 method();dialog.querySelector('#plenary-variant').onchange=e=>{p.variant=+e.target.value;method();save();};dialog.querySelectorAll('[data-plenary-field]').forEach(t=>t.oninput=()=>{p[t.dataset.plenaryField]=t.value;save();});dialog.querySelector('#close-plenary').onclick=()=>dialog.close();dialog.querySelector('#plenary-save').onclick=saveFile;
 dialog.querySelector('#plenary-text').onclick=()=>{recordDownload(new Blob([c.title+'\nShared class record\n\n'+Object.entries(labels).map(([k,l])=>l+'\n'+p[k]).join('\n\n')],{type:'text/plain;charset=utf-8'}),'txt');};
 dialog.querySelector('#plenary-pdf').onclick=async e=>{e.target.disabled=true;const snapshot=structuredClone(work);try{const doc=Portfolio.makePdf(window.jspdf.jsPDF,snapshot,COURSE,'plenary:'+id,await font());recordDownload(doc.output('blob'),'pdf');}catch(err){dialog.querySelector('#plenary-status').textContent=err.message;}finally{e.target.disabled=false;}};
 if(!dialog.open)dialog.showModal();
 }
 function recordDownload(blob,ext){if(recordUrl)URL.revokeObjectURL(recordUrl);const name=`britain-${recordId}-class-record.${ext}`;recordUrl=download(blob,name);dialog.querySelector('#plenary-status').innerHTML=`Sicherung erstellt. <a href="${recordUrl}" download="${name}">Nochmals herunterladen</a>`;}
 function mountAI(c,f){const host=document.querySelector(`#answer-${f[0]}`).closest('.field');const saved=work.chapters[c.id].ai[f[0]];const panel=document.createElement('details');panel.className='ai-panel';panel.innerHTML=`<summary>KI-Schreibfeedback · 0–15 Übungspunkte</summary><p>Rückmeldung auf LK-13-Niveau zu dieser Aufgabe. Übungseinschätzung, keine verbindliche Schulnote. Inhalt 40 %, Sprache 60 % (Wortschatz, Grammatik und Textgestaltung gleich gewichtet).</p>${BRITAIN_AI.enabled?`<p>Nur dieser Antworttext wird nach deinem Klick über Cloudflare an OpenAI gesendet. Name, Klasse, andere Antworten und Plenumsprotokoll werden nicht mitgesendet. Bitte keine persönlichen Daten in den Text schreiben.</p><label>Übungscode<input type="password" class="ai-code" autocomplete="off" maxlength="100"></label><label class="check"><input type="checkbox" class="ai-consent">Ich möchte diesen Text zur KI-Korrektur senden.</label><button class="quiet ai-submit">Diesen Text korrigieren</button>`:'<p>Die Korrektur wird für diesen Kurs eingerichtet. Deine Antworten bleiben bis zur Freischaltung auf deinem Gerät.</p>'}<p role="status" class="ai-status"></p><div class="ai-feedback"></div>`;
 host.append(panel);const result=panel.querySelector('.ai-feedback');if(saved)showFeedback(result,saved,work.chapters[c.id].answers[f[0]]);
 if(!BRITAIN_AI.enabled)return;
 panel.querySelector('.ai-submit').onclick=async()=>{
  const status=panel.querySelector('.ai-status'),text=work.chapters[c.id].answers[f[0]]||'',code=panel.querySelector('.ai-code').value.trim();
  if(requestPending){status.textContent='Es läuft bereits eine Korrektur. Bitte warte.';return;}
  if(!panel.querySelector('.ai-consent').checked){status.textContent='Bitte bestätige die Übermittlung dieses Textes.';return;}
  if(!/^[A-Za-z2-9]{6}$/.test(code)&&code.length<16){status.textContent='Bitte gib deinen Übungscode ein.';return;}
  if(words(text)<15||text.length>16000){status.textContent='Bitte 15 Wörter bis maximal 16.000 Zeichen einreichen.';return;}
  requestPending=true;panel.querySelector('.ai-submit').disabled=true;status.textContent='Dein Text wird geprüft …';const targetWork=work;
  try{const r=await fetch(BRITAIN_AI.endpoint,{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+code},body:JSON.stringify({taskId:c.id+':'+f[0],text}),signal:AbortSignal.timeout(75000)});const response=await r.json();if(!r.ok)throw new Error(response.error||'Der Korrekturdienst ist gerade nicht erreichbar.');if(typeof response.feedback!=='string'||response.feedback.length>20000)throw new Error('Die Rückmeldung ist unvollständig.');const entry={draft:text,feedback:response.feedback,date:new Date().toISOString()};if(work!==targetWork){status.textContent='Inzwischen wurde ein anderer Arbeitsstand geladen. Die Rückmeldung wurde nicht darin gespeichert.';showFeedback(result,entry,text);return;}work.chapters[c.id].ai[f[0]]=entry;save();showFeedback(result,entry,work.chapters[c.id].answers[f[0]]);status.textContent='Rückmeldung gespeichert. Überarbeite selbst; dein Text wurde nicht ersetzt.';}
  catch(err){status.textContent=err.name==='TimeoutError'?'Die Korrektur dauert zu lange. Dein Text bleibt erhalten.':err.message;}
  finally{requestPending=false;panel.querySelector('.ai-submit').disabled=false;}
 };
 const input=document.querySelector(`#answer-${f[0]}`);input.addEventListener('input',()=>{const entry=work.chapters[c.id].ai[f[0]];if(entry)showFeedback(result,entry,input.value);});
 }
 function showFeedback(el,entry,current){el.replaceChildren();if(entry.draft!==current){const warning=document.createElement('p');warning.textContent='Rückmeldung zu einer früheren Fassung — dein Text wurde inzwischen verändert.';el.append(warning);}const p=document.createElement('div');p.className='review-text';p.textContent=entry.feedback;el.append(p);}
 return {mount,openPlenary};
})();
