/* Image-faithful course-book reader. Markings use page-relative coordinates. */
const READINGS={orwell:{title:'Shooting an Elephant',author:'George Orwell',start:8,end:19,textEnd:15},kureishi:{title:'My Son the Fanatic',author:'Hanif Kureishi',start:20,end:33,textEnd:29},smith:{title:'The Embassy of Cambodia',author:'Zadie Smith',start:34,end:57,textEnd:51},transfer:{title:'Post-reading texts',author:'Course-book transfer',start:58,end:65,textEnd:65}};
let reading='orwell',readingPage=8,marking=false,markColour='yellow',dragMark=null,readerPdfUrl=null;
const COLOURS={yellow:'#ffe04b',blue:'#52c9ff',pink:'#ff86b5'};
const reader=document.createElement('dialog');reader.id='reader';reader.setAttribute('aria-labelledby','reader-title');
reader.innerHTML=`<div class="reader-head"><div><span class="eyebrow" id="reader-author"></span><h2 id="reader-title"></h2></div><button class="quiet" id="reader-close" aria-label="Lesebereich schließen">Schließen ×</button></div><div class="reader-tools"><button class="quiet" id="reader-prev" aria-label="Vorherige Buchseite">←</button><label for="reader-page">Buchseite</label><select id="reader-page"></select><button class="quiet" id="reader-next" aria-label="Nächste Buchseite">→</button><button class="quiet" id="reader-mark" aria-pressed="false">Markieren: aus</button><label for="reader-colour">Farbe</label><select id="reader-colour"><option value="yellow">Gelb</option><option value="blue">Blau</option><option value="pink">Rosa</option></select><button class="quiet" id="reader-undo">Letzte Markierung löschen</button><label for="reader-zoom">Ansicht</label><select id="reader-zoom"><option value="fit">Seitenbreite</option><option value="125">125 %</option><option value="160">160 %</option></select></div><p class="reader-help">Zum Markieren einschalten und mit Stift oder Maus über eine Textzeile ziehen. Mehrere Zeilen einzeln markieren. Zum Scrollen oder Vergrößern Markieren ausschalten. Alle Markierungen und Seitennotizen werden im Arbeitsstand gespeichert.</p><div class="reader-scroll"><div class="reader-sheet"><img id="reader-image" alt=""><canvas id="reader-canvas" aria-label="Markierungsfläche über der Buchseite"></canvas></div></div><div class="reader-notes"><label for="reader-note">Notiz zu dieser Seite · Zitat, Zeilenangabe, Deutung</label><textarea id="reader-note" maxlength="10000" placeholder="Evidence → interpretation → connection"></textarea></div><div class="reader-actions"><a id="reader-original" target="_blank" rel="noopener">Original als PDF öffnen ↗</a><button class="quiet" id="reader-save">Arbeitsstand mit Markierungen sichern ↓</button><button class="primary" id="reader-export">Markierte Seiten als PDF ↓</button></div><p id="reader-status" role="status"></p>`;
document.body.append(reader);
function readerKey(){return reading+':'+readingPage;}
function markers(){return work.markings[readerKey()]||[];}
function readingIds(c){if(!c)return Object.keys(READINGS);if(c.id.startsWith('cambodia'))return ['smith'];if(['fanatic-entry','fanatic-language','fanatic-deeper','diversity'].includes(c.id))return ['kureishi'];if(['comparison','crashcourse'].includes(c.id))return ['orwell','kureishi'];if(c.id==='beyond')return ['transfer','orwell','kureishi','smith'];if(c.id==='final')return ['orwell','kureishi','smith'];return ['orwell'];}
function readerButtons(c){return '<div class="reader-sidebar"><h3>Texte & Markierungen</h3>'+readingIds(c).map(id=>`<button class="reader-launch quiet" data-reading="${id}"><b>${esc(READINGS[id].title)}</b><span>Originalseiten ${READINGS[id].start}–${READINGS[id].end} · Lesen & markieren</span></button>`).join('')+'<p class="source">Buchseiten mit Zeilenangaben und Aufgaben. Deine Markierungen bleiben in deinem Portfolio.</p></div>';}
function bindReaders(){document.querySelectorAll('[data-reading]').forEach(b=>b.onclick=()=>openReader(b.dataset.reading));}
function openReader(id){if(!READINGS[id])return;reading=id;readingPage=READINGS[id].start;$('#reader-title').textContent=READINGS[id].title;$('#reader-author').textContent=READINGS[id].author;$('#reader-page').innerHTML=Array.from({length:READINGS[id].end-READINGS[id].start+1},(_,i)=>{const n=READINGS[id].start+i;return `<option value="${n}">${n}${n>READINGS[id].textEnd?' · Aufgaben':''}</option>`}).join('');$('#reader-original').href=id+'-reading.pdf';$('#reader-status').textContent='';setMarking(false);showReadingPage();reader.showModal();}
function setMarking(value){marking=value;$('#reader-mark').setAttribute('aria-pressed',String(marking));$('#reader-mark').textContent='Markieren: '+(marking?'an':'aus');reader.classList.toggle('is-marking',marking);dragMark=null;drawMarkers();}
function showReadingPage(){dragMark=null;$('#reader-page').value=String(readingPage);$('#reader-image').alt=`${READINGS[reading].title} · Original-Buchseite ${readingPage}. Text mit Zeilenangaben. Alternative Ansicht: Original-PDF.`;$('#reader-image').src='book-'+readingPage+'.jpg';$('#reader-prev').disabled=readingPage===READINGS[reading].start;$('#reader-next').disabled=readingPage===READINGS[reading].end;$('#reader-note').value=work.readingNotes[readerKey()]||'';$('.reader-scroll').scrollTop=0;drawMarkers();}
function drawMarkers(){const canvas=$('#reader-canvas'),img=$('#reader-image');if(!img.naturalWidth)return;canvas.width=img.naturalWidth;canvas.height=img.naturalHeight;const ctx=canvas.getContext('2d');for(const m of [...markers(),...(dragMark?[dragMark]:[])]){ctx.fillStyle=COLOURS[m.color];ctx.globalAlpha=.35;ctx.fillRect(m.x*canvas.width,m.y*canvas.height,m.w*canvas.width,m.h*canvas.height);}ctx.globalAlpha=1;$('#reader-undo').disabled=markers().length===0;}
$('#reader-image').onload=drawMarkers;$('#reader-image').onerror=()=>{$('#reader-status').textContent='Die Buchseite konnte nicht geladen werden. Bitte Verbindung prüfen oder das Original-PDF öffnen.'};
const cv=$('#reader-canvas');let origin=null;
function position(e){const b=cv.getBoundingClientRect();return {x:Math.max(0,Math.min(1,(e.clientX-b.left)/b.width)),y:Math.max(0,Math.min(1,(e.clientY-b.top)/b.height))};}
cv.onpointerdown=e=>{if(!marking||e.button!==0||origin)return;e.preventDefault();origin={...position(e),id:e.pointerId};cv.setPointerCapture(e.pointerId);};
cv.onpointermove=e=>{if(!origin||origin.id!==e.pointerId)return;e.preventDefault();const p=position(e);dragMark={x:Math.min(origin.x,p.x),y:Math.min(origin.y,p.y),w:Math.abs(p.x-origin.x),h:Math.max(.011,Math.abs(p.y-origin.y)),color:markColour};if(dragMark.y+dragMark.h>1)dragMark.h=1-dragMark.y;drawMarkers();};
cv.onpointerup=e=>{if(!origin||origin.id!==e.pointerId)return;if(dragMark&&dragMark.w>.004){if(markers().length>=200){$('#reader-status').textContent='Maximal 200 Markierungen pro Seite. Bitte zuerst eine Markierung löschen.';}else{work.markings[readerKey()]=[...markers(),dragMark];save();$('#reader-status').textContent='Markierung gespeichert · Arbeitsdatei regelmäßig sichern.';}}origin=null;dragMark=null;drawMarkers();};
cv.onpointercancel=()=>{origin=null;dragMark=null;drawMarkers()};
$('#reader-close').onclick=()=>reader.close();reader.onclose=()=>{origin=null;dragMark=null};$('#reader-mark').onclick=()=>setMarking(!marking);$('#reader-colour').onchange=e=>markColour=e.target.value;$('#reader-page').onchange=e=>{readingPage=+e.target.value;showReadingPage()};$('#reader-prev').onclick=()=>{readingPage--;showReadingPage()};$('#reader-next').onclick=()=>{readingPage++;showReadingPage()};$('#reader-undo').onclick=()=>{work.markings[readerKey()]=markers().slice(0,-1);save();drawMarkers();$('#reader-status').textContent='Letzte Markierung entfernt.'};$('#reader-note').oninput=e=>{work.readingNotes[readerKey()]=e.target.value;save()};$('#reader-zoom').onchange=e=>{$('.reader-sheet').style.width=e.target.value==='fit'?'100%':e.target.value+'%'};$('#reader-save').onclick=()=>{saveFile();$('#reader-status').textContent='Arbeitsdatei mit Antworten, Markierungen und Seitennotizen erstellt.'};
function loadReadingImage(page){return new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=()=>reject(new Error('Buchseite '+page+' konnte nicht geladen werden.'));img.src='book-'+page+'.jpg';});}
async function markedPdf(){
 const btn=$('#reader-export');btn.disabled=true;$('#reader-status').textContent='Markierte Seiten werden als PDF zusammengestellt…';
 try{const id=reading,r=READINGS[id],snapshot=structuredClone(work),pages=[];for(let n=r.start;n<=r.end;n++)if(snapshot.markings[id+':'+n]?.length||snapshot.readingNotes[id+':'+n]?.trim())pages.push(n);if(!pages.length)pages.push(readingPage);
 const doc=new window.jspdf.jsPDF({unit:'mm',format:'a4',compress:true});doc.addFileToVFS('NotoSans.ttf',await font());doc.addFont('NotoSans.ttf','NotoSans','normal');doc.setFont('NotoSans');doc.setProperties({title:r.title+' · Markierungen',author:snapshot.profile.name||'Learner'});
 for(let i=0;i<pages.length;i++){const n=pages[i],im=await loadReadingImage(n);if(i)doc.addPage();const canvas=document.createElement('canvas');canvas.width=im.naturalWidth;canvas.height=im.naturalHeight;const ctx=canvas.getContext('2d');ctx.drawImage(im,0,0);ctx.globalAlpha=.35;for(const m of snapshot.markings[id+':'+n]||[]){ctx.fillStyle=COLOURS[m.color];ctx.fillRect(m.x*canvas.width,m.y*canvas.height,m.w*canvas.width,m.h*canvas.height);}doc.addImage(canvas.toDataURL('image/jpeg',.9),'JPEG',0,0,210,297,undefined,'FAST');const note=snapshot.readingNotes[id+':'+n];if(note?.trim()){doc.addPage();doc.setFontSize(16);doc.text('Notizen · Buchseite '+n,20,25);doc.setFontSize(11);let y=40;for(const line of doc.splitTextToSize(note.replace(/→/g,' -> '),170)){if(y>275){doc.addPage();y=25;}doc.text(line,20,y);y+=6;}}}
 const blob=doc.output('blob'),name=`${id}-marked-${timestamp()}.pdf`;if(readerPdfUrl)URL.revokeObjectURL(readerPdfUrl);readerPdfUrl=download(blob,name);$('#reader-status').innerHTML=`${pages.length} Buchseite(n) exportiert. <a href="${readerPdfUrl}" target="_blank" rel="noopener">PDF öffnen ↗</a> · <a href="${readerPdfUrl}" download="${name}">PDF herunterladen ↓</a>`;
 const file=new File([blob],name,{type:'application/pdf'});if(navigator.canShare?.({files:[file]})){const share=document.createElement('button');share.className='quiet';share.textContent='Teilen / In Dateien sichern';share.onclick=async()=>{try{await navigator.share({files:[file]})}catch(e){if(e.name!=='AbortError')$('#reader-status').append(' Bitte PDF öffnen und dort teilen.');}};$('#reader-status').append(share)}
 }catch(e){$('#reader-status').textContent=e.message;}finally{btn.disabled=false;}
}
$('#reader-export').onclick=markedPdf;
const baseRender=render;render=function(){baseRender();if(!teacher){const c=COURSE.find(c=>c.id===work.active);if(c){$('#companion').insertAdjacentHTML('afterbegin',readerButtons(c));let quick=document.querySelector('#reader-quick-links');if(!quick){quick=document.createElement('nav');quick.id='reader-quick-links';quick.setAttribute('aria-label','Open reading texts');document.querySelector('.input-toolbar').after(quick);}quick.innerHTML=readingIds(c).map(id=>'<button class="quiet" data-reading="'+id+'">Lesetext: '+esc(READINGS[id].title)+' ↗</button>').join('');}else{$('#overview').insertAdjacentHTML('beforeend','<section class="overview-readings"><h2>Die Texte griffbereit</h2>'+readerButtons(null)+'</section>');}bindReaders();}};render();
